
services:
  # api_heroes: 
  #   container_name: api_heroes
  #   build: .
  #   ports:
  #     - "${PORT_SERVER:-3003}:${PORT_SERVER:-3003}"
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER:-root}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345678}
  #     POSTGRES_DB: ${POSTGRES_DB:-heroes}
  #     DATABASE_URL: postgres://${POSTGRES_USER:-root}:${POSTGRES_PASSWORD:-12345678}@postgres:5432/${POSTGRES_DB:-heroes}
  #   depends_on:
  #     - postgres
  #   networks:
  #     - postgres
  #   restart: unless-stopped

  postgres_preco_justo:
    container_name: postgres_preco_justo
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345678}
      POSTGRES_DB: ${POSTGRES_DB:-preco_justo}
      PGDATA: /data/postgres
    volumes:
       - postgres_preco_justo:/data/postgres
    ports:
      - "5453:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin_preco_justo:
    container_name: pgadmin_preco_justo
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-jander.webmaster@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-12345678}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin_preco_justo:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5051}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres_preco_justo:
    pgadmin_preco_justo:
